apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourceName": "bmn-sriov-numa0p0-pf1",
                "resourcePrefix": "kinara.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0000:02:00.0#0-7"
                    ]
                }
            },
            {
                "resourceName": "bmn-sriov-numa0p1-pf2",
                "resourcePrefix": "kinara.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0000:02:00.1#0-7"
                    ]
                }
            },
            {
                "resourceName": "bmn-sriov-numa1p0-pf3",
                "resourcePrefix": "kinara.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0001:16:00.0#0-7"
                    ]
                }
            },
            {
                "resourceName": "bmn-sriov-numa1p1-pf4",
                "resourcePrefix": "kinara.com",
                "selectors": {
                    "vendors": [
                        "15b3"
                    ],
                    "devices": [
                        "101e"
                    ],
                    "drivers": [
                        "mlx5_core"
                    ],
                    "rootDevices": [
                        "0001:16:00.1#0-7"
                    ]
                }
            }
        ]
    }